name: Experience Japan Beauty Products
favicon: null
layout_spectrum: 0.19849777594208717
typography_spectrum: 0.22954
title: Experience Japan Beauty Products
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ed99bb'
    - '#e9c6b3'
    - '#a31e53'
    - '#0d0e12'
    - '#8f5352'
  brandStrength: 0.125
  lightness: 0.3048395267687738
  saturation: 0.5625
  rhythmicContrast: 0.6471708531025797
purpose: []
